[package]
name = "rustypass"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
cocoon = "0.4.2"
dotenv = "0.15.0"
sha3 = "0.10.8"
rpassword = "7.3.1"
hex = "0.4.3"